version: '3'
services:
    app:
        image: app
        container_name: app
        links:
            - mysql:container_mysql
        environment:
            APP_ENV: dev
        ports:
            - 80:80
            - 9000:9000
        volumes:
            - ./docker/conf/supervisor/conf-available:/etc/supervisor/conf-available
            - ./docker/conf/nginx/sites-available:/etc/nginx/sites-available
            - ./docker/conf/nginx/fastcgi_params:/etc/nginx/fastcgi_params
            - ./docker/conf/nginx/mime.types:/etc/nginx/mime.types
            - ./docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/conf/logs:/var/www/logs
            - ./server:/var/www/html/server
            - ./client:/var/www/html/client

    mysql:
        image: app_mysql
        container_name: mysql
        ports:
            - 3306:3306
        volumes:
            - ./docker/etc/mysql/my.cnf:/etc/mysql/my.cnf
            - ./docker/etc/mysql/lib:/var/lib/mysql
            - ./docker/etc/mysql/logs:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root